draw_config:
  key_w: 70.0
  key_h: 60.0
  split_gap: 30.0
  combo_w: 30.0
  combo_h: 28.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: true
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: |
    /* For default styles, see https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L85 */

    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
    }

    /* Color accent for held keys */
    rect.held, rect.combo.held {
        fill: #ffc;
    }

    /* Technique borrowed and extended from https://github.com/englmaxi/zmk-config/blob/master/keymap-drawer/config.yaml */
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
    }
    .hold {
      translate: 0px -8px;
      font-size: 10px;
      opacity: 1.0;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Toggle */
    .toggle.shifted {
      translate: -10px 12px;
    }

    .toggle.hold {
      translate: 13px -23px;
    }

    /* Variant for tap-dances */
    .tap_dance.tap {
      translate: -7px 0px;
      font-size: 12px;
    }
    .tap_dance.shifted {
      translate: 7px 17px;
      font-size: 12px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 12px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.tap {
      translate: -35px 0px;
    }
    .combo.sym_by_sym.shifted {
      translate: 35px 20px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.hold {
      visibility: hidden;
    }

    /* hide hold box for combo sym_by_sym */
    .combo.sym_by_sym.hold > path[stroke="none"][fill="none"] {
      visibility: hidden;
    }
  footer_text: ''
  shrink_wide_legends: 6
  style_layer_activators: true
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true
parse_config:
  zmk_additional_includes: 
    - "zmk-helpers/include"
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    "&key_repeat": "$$mdi:repeat$$"
    "&sys_reset": "$$mdi:restart$$"
    "&bootloader": "$$mdi:cog-transfer$$"
    "&tog LOCK": "$$mdi:lock$$"
    "&studio_unlock": "⌨️ ZMK Studio"
    "&unstick": "ModKey Reset"
    # "&bt BT_CLR": "$$mdi:bluetooth-transfer$$"
    # "&out OUT_USB": "$$mdi:usb$$"
    # "&out OUT_BLE": "$$mdi:bluetooth$$"
    # "&bt BT_SEL 0": "⌨️ 0 👨‍💻"
    # "&bt BT_SEL 1": "⌨️ 1 📱"
    # "&bt BT_SEL 2": "⌨️ 2 💻"
    # "&bt BT_SEL 3": "⌨️ 3 tablet"
    # "&bt BT_SEL 4": "⌨️ 4 🪟"
    "&kp C_NEXT": "⏭️ Next"
    "&kp C_BRI_UP": "💡 Up"
    "&kp C_FF": "⏩ Fast Forward"
    "&kp C_PWR": "🔘 Power"
    "&kp C_VOL_DN": "🔉 Down"
    "&kp C_VOL_UP": "🔊 Up"
    "&kp C_PREV": "⏮️ Prev"
    "&kp C_BRI_DN": "💡 Down"
    "&kp C_RW": "⏪ Rewind"
    "&kp C_SLEEP": "💤 Sleep"
    "&kp C_MUTE": "🔇 Mute"
    "&kp LC(LA(M))": "🎤 MicMute"
    "&kp C_PP": "⏯️ PlayPause"
    "&kp C_EJECT": "⏏️ Eject"
    "&kp K_LOCK": "🔐 Lock"
    "&m_env": "📩 ENV"
    "&m_proc": "📩 Process"
    "&m_today": "📅 Today"
    "&m_week": "📆 Soon"
    "&m_month": "📆 Later"
    "&m_cust": "💲 Customer"
    "&m_arch": "📝 Arch"
    "&m_info": "📰 Info"
    "&m_plm": "👨‍🏫"
    "&m_lt": "👨‍💼 LT"
    "&m_choose": "📁 Select"
    "&m_maillist": "📑👈 List"
    "&m_teamfwd": "👨‍🔧 Team"
    "&m_calendar": "📅 Cal"
    "&m_inbox": "📥 Inbox"
    "&m_dirprev": "🗂️🔼 Prev"
    "&m_dirnext": "🗂️🔽 Next"
    "&m_mailcp": "✉️✉️ Copy"
    "&m_mailtext": "👉🖹 Content"
    "&m_emoj_td": "👎"
    "&m_emoj_tu": "👍"
    "&m_emoj_h": "😀"
    "&m_emoj_u": "🤔"
    "&m_emoj_w": "😉"
    "&m_emoj_s": "😟"
    "&m_emoj_l": "🤣"
    "&m_emoj_j": "😜"
    "&td_ctrl_cx":
      tap: "CS+C"
      shifted: "CS+X"
    "&kp PT_C_CEDILLA": "Ç"
    "&kp PT_MINUS": "-"
    "&kp LEFT": "⬅️"
    "&kp RIGHT": "➡️"
    "&kp UP": "⬆️"
    "&kp DOWN": "⬇️"
    '&out OUT_BLE':
      tap: $$mdi:keyboard$$
      shifted: $$mdi:bluetooth$$
      type: sym_by_sym
    '&out OUT_USB':
      tap: $$mdi:keyboard$$
      shifted: $$mdi:usb$$
      type: sym_by_sym
    '&out OUT_TOG':
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
      shifted: $$mdi:usb$$
      type: toggle
    '&capsw': $$mdi:alphabetical-variant$$
    '&m_dblclk':
      tap: $$mdi:cursor-default-click$$
      shifted: "2x"
      type: sym_sub_text
    '&mkp LCLK':
      tap: $$mdi:cursor-default-click$$
      shifted: "L"
      type: sym_sub_text
    '&mkp MCLK':
      tap: $$mdi:cursor-default-click$$
      shifted: "M"
      type: sym_sub_text
    '&mkp RCLK':
      tap: $$mdi:cursor-default-click$$
      shifted: "R"
      type: sym_sub_text
    '&mkp MB4':
      tap: $$mdi:cursor-default-click$$
      shifted: "4"
      type: sym_sub_text
    '&mkp MB5':
      tap: $$mdi:cursor-default-click$$
      shifted: "5"
      type: sym_sub_text
    '&bt BT_CLR':
      tap: $$mdi:bluetooth-settings$$
      shifted: $$mdi:close-thick$$
      type: sym_sub_text
    '&bt BT_CLR_ALL':
      tap: $$mdi:bluetooth-settings$$
      shifted: $$mdi:close-thick$$
      hold: $$mdi:asterisk$$
      type: sym_sub_text
    '&bt BT_SEL 0':
      tap: $$mdi:bluetooth-connect$$
      shifted: '0'
      type: sym_sub_text
    '&bt BT_SEL 1':
      tap: $$mdi:bluetooth-connect$$
      shifted: '1'
      type: sym_sub_text
    '&bt BT_SEL 2':
      tap: $$mdi:bluetooth-connect$$
      shifted: '2'
      type: sym_sub_text
    '&bt BT_SEL 3':
      tap: $$mdi:bluetooth-connect$$
      shifted: '3'
      type: sym_sub_text
    '&bt BT_SEL 4':
      tap: $$mdi:bluetooth-connect$$
      shifted: '4'
      type: sym_sub_text
    '&msc SCRL_LEFT':
      tap: '$$mdi:mouse-scroll-wheel$$'
      shifted: $$mdi:arrow-left$$
      type:    sym_by_sym
    '&msc SCRL_UP':
      tap: '$$mdi:mouse-scroll-wheel$$'
      shifted: $$mdi:arrow-up$$
      type:    sym_by_sym
    '&msc SCRL_DOWN':
      tap: '$$mdi:mouse-scroll-wheel$$'
      shifted: $$mdi:arrow-down$$
      type:    sym_by_sym
    '&msc SCRL_RIGHT':
      tap: '$$mdi:mouse-scroll-wheel$$'
      shifted: $$mdi:arrow-right$$
      type:    sym_by_sym
    '&mmv MOVE_LEFT':
      tap:     $$mdi:tortoise$$
      shifted: $$mdi:arrow-left$$
      type:    sym_by_sym
    '&mmv MOVE_RIGHT':
      tap:     $$mdi:tortoise$$
      shifted: $$mdi:arrow-right$$
      type:    sym_by_sym
    '&mmv MOVE_UP':
      tap:     $$mdi:tortoise$$
      shifted: $$mdi:arrow-up$$
      type:    sym_by_sym
    '&mmv MOVE_DOWN':
      tap:     $$mdi:tortoise$$
      shifted: $$mdi:arrow-down$$
      type:    sym_by_sym
  sticky_label: sticky
  toggle_label: $$mdi:toggle-switch$$
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: true
  modifier_fn_map:
    left_ctrl: C
    right_ctrl: C
    left_shift: S
    right_shift: S
    left_alt: A
    right_alt: AGr
    left_gui: G
    right_gui: G
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix:
  - PT
  zmk_keycode_map:
    EXCLAMATION: '!'
    EXCL: '!'
    PT_EXCL: '!'
    AT_SIGN: '@'
    AT: '@'
    PT_AT: '@'
    HASH: '#'
    PT_HASH: '#'
    POUND: '#'
    DOLLAR: $
    DLLR: $
    PT_DLLR: $
    PERCENT: '%'
    PRCNT: '%'
    PT_PRCNT: '%'
    CARET: ^
    PT_CARET: ^
    AMPERSAND: '&'
    AMPS: '&'
    PT_AMPS: '&'
    ASTERISK: '*'
    ASTRK: '*'
    STAR: '*'
    PT_STAR: '*'
    LEFT_PARENTHESIS: (
    LPAR: (
    PT_LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    PT_RPAR: )
    EQUAL: '='
    PT_EQUAL: '='
    PLUS: +
    PT_PLUS: +
    MINUS: '-'
    PT_MINUS: '-'
    UNDERSCORE: _
    UNDER: _
    PT_UNDER: _
    SLASH: /
    FSLH: /
    PT_FSLH: /
    QUESTION: '?'
    QMARK: '?'
    PT_QMARK: '?'
    BACKSLASH: \
    BSLH: \
    PT_BSLH: \
    PIPE: '|'
    PT_PIPE: '|'
    NON_US_BACKSLASH: \
    PIPE2: '|'
    NON_US_BSLH: '|'
    SEMICOLON: ;
    SEMI: ;
    COLON: ':'
    SINGLE_QUOTE: ''''
    SQT: ''''
    PT_SQT: ''''
    APOSTROPHE: ''''
    APOS: ''''
    DOUBLE_QUOTES: '"'
    DQT: '"'
    PT_DQT: '"'
    COMMA: ','
    LESS_THAN: <
    LT: <
    PT_LT: <
    PERIOD: .
    DOT: .
    PT_DOT: .
    GREATER_THAN: '>'
    GT: '>'
    PT_GT: '>'
    LEFT_BRACKET: '['
    LBKT: '['
    PT_LBKT: '['
    LEFT_BRACE: '{'
    LBRC: '{'
    PT_LBRC: '{'
    RIGHT_BRACKET: ']'
    RBKT: ']'
    PT_RBKT: ']'
    RIGHT_BRACE: '}'
    RBRC: '}'
    PT_RBRC: '}'
    GRAVE: '`'
    PT_GRAVE: '`'
    PT_ACUTE: '´'
    PT_UMLAUT: '¨'
    TILDE: '~'
    PT_TILDE: '~'
    NON_US_HASH: '#'
    PT_LAQUO: '«'
    PT_ORDF: 'º'
    PT_EURO: '€'
    PT_SECT: '§'
    NUHS: '#'
    TILDE2: '~'
    PAGE_UP: 'PgUp'
    PAGE_DOWN: 'PgDn'
    HOME: 'Home'
    END: 'End'
    ESC: 'Esc'
    GLOBE: $$tabler:world$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE: $$mdi:backspace-outline$$
    DELETE: $$mdi:backspace-reverse-outline$$
    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    C_MUTE: $$mdi:volume-mute$$
    C_VOL_UP: $$mdi:volume-plus$$
    C_VOL_DN: $$mdi:volume-minus$$
    C_BRI_UP: $$tabler:brightness-up$$
    C_BRI_DN: $$tabler:brightness-down$$
    C_POWER: $$mdi:power$$
    C_SLEEP: $$mdi:power-sleep$$
    UP: $$mdi:arrow-up$$
    DOWN: $$mdi:arrow-down$$
    LEFT: $$mdi:arrow-left$$
    RIGHT: $$mdi:arrow-right$$
    RETURN: ⮐
    RET: ⮐
    KP_NUMLOCK: Numlock
    TAB: $$mdi:keyboard-tab$$
    LEFT_GUI: $$mdi:penguin$$
    LGUI: $$mdi:penguin$$
    RIGHT_GUI: $$mdi:penguin$$
    RGUI: $$mdi:penguin$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    LALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    RA(S): 'ß'
    # LC(LA(LS(J))): $$mdi:face$$
    Meh-J: $$mdi:face$$
  zmk_combos:
    combo_toggle_lock_left: { align: mid, layers: [LOCK]}
    combo_toggle_lock_right: { align: mid, layers: [LOCK]}
    # combo_esc: { align: top, o: 3.00, arc_scale: 1.00}
    # combo_tab: { align: top, o: 3.00, arc_scale: 1.00}
    # combo_ret: { align: top, o: 3.00, arc_scale: 1.00}
    # combo_at: { align: top, o: 3.00, arc_scale: 1.00}
    # combo_capsword: { align: top, o: 3.00, arc_scale: 1.00}
    combo_bspc: { align: mid, o: 0.00, arc_scale: 1.00}
    combo_ctrlbspc: { align: mid, o: 0.00, arc_scale: 1.00}
    combo_del: { align: mid, o: 0.00, arc_scale: 1.00}
    # combo_repeat_right: { align: top, o: 3.00, arc_scale: 1.00}
    # combo_sz: { align: top, o: 3.00, arc_scale: 1.00}
    # combo_pup: { align: top, o: 3.00, arc_scale: 1.00}
    # combo_down: { align: top, o: 3.00, arc_scale: 1.00}
    # combo_prtwin: { align: top, o: 3.00, arc_scale: 1.00}
    # combo_underscore: { align: top, o: 3.00, arc_scale: 1.00}
    # combo_ctrlshiftx: { align: top, o: 0.00, arc_scale: 1.00}
    # combo_ctrlshiftc: { align: top, o: 1.20, arc_scale: 1.00}
    combo_ctrlshiftcx: { align: top, o: 1.30, arc_scale: 1.00}
    combo_ctrlshiftv: { align: bottom, o: 0.30, arc_scale: 1.00}
    combo_ctrla: { align: mid, o: 0.00, arc_scale: 1.00}
    combo_ctrlz: { align: mid, o: 0.00, arc_scale: 1.00}
    # combo_leader: { align: top, o: 3.00, arc_scale: 1.00}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
