---
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # - name: urob
      # url-base: https://github.com/urob
    # - name: dddelispt42
    #   url-base: https://github.com/dddelispt42
  projects:
    - name: zmk
      remote: zmkfirmware
      # remote: urob
      # remote: dddelispt42
      revision: main
      import: app/west.yml
  self:
    path: config
